//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';
export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';
export const OTP_ENABLE_LOADER = 'OTP_ENABLE_LOADER';
export const OTP_DISABLE_LOADER = 'OTP_DISABLE_LOADER';
export const FORGOT_ENABLE_LOADER = 'FORGOT_ENABLE_LOADER';
export const FORGOT_DISABLE_LOADER = 'FORGOT_DISABLE_LOADER';
export const RESET_PASSWORD_ENABLE_LOADER = 'RESET_PASSWORD_ENABLE_LOADER';
export const RESET_PASSWORD_DISABLE_LOADER = 'RESET_PASSWORD_DISABLE_LOADER';

//theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

//signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

//OTp
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_RESPONSE = 'OTP_RESPONSE';
export const OTP_FAILED = 'OTP_FAILED';

//forgot password
export const FORGOT_REQUEST = 'FORGOT_REQUEST';
export const FORGOT_RESPONSE = 'FORGOT_RESPONSE';
export const FORGOT_FAILED = 'FORGOT_FAILED';
//reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_RESPONSE = 'RESET_PASSWORD_RESPONSE';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const LOADING_ITEM = 'LOADING_ITEM';
//data
export const GET_SLIDER_DATA = 'GET_SLIDER_DATA';
export const LOADING_SLIDER_DATA = 'LOADING_SLIDER_DATA';
export const GET_MOST_POPULAR = 'GET_MOST_POPULAR';
export const LOADING_POPULAR_DATA = 'LOADING_POPULAR_DATA';
export const CLEAR_ITEM_LIST = 'CLEAR_ITEM_LIST';

export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY_ITEMS = 'GET_CATEGORY_ITEMS';
export const LOADING_CATEGORY_ITEMS = 'LOADING_CATEGORY_ITEMS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const LOADING_CART = 'LOADING_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const EMPTY_CART = 'EMPTY_CART';

//Tables
export const LOADING_NORMAL_TABLE = 'LOADING_NORMAL_TABLE';
export const GET_NORMAL_TABLES = 'GET_NORMAL_TABLES';
export const SET_NORMAL_TABLES = 'SET_NORMAL_TABLES';
export const LOADING_COUPLES_TABLE = 'LOADING_COUPLES_TABLE';
export const GET_COUPLE_TABLES = 'GET_COUPLE_TABLES';
export const SET_COUPLES_TABLE = 'SET_COUPLES_TABLE';

export const BOOK_TABLE = 'BOOK_TABLE';
export const LOADING_BOOK_TABLE = 'LOADING_BOOK_TABLE';

//user
export const LOADING_USER_BOOKINGS = 'LOADING_USER_BOOKINGS';
export const ADD_USER_BOOKINGS = 'ADD_USER_BOOKINGS';
