export default [
  {
    id: 1,
    name: 'South Indian',
    image: require('app/assets/images/categories/southindian.jpeg'),
    loading: false,
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
  {
    id: 2,
    name: 'Continental',
    image: require('app/assets/images/categories/continental.jpg'),
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
  {
    id: 3,
    name: 'Beverages',
    image: require('app/assets/images/categories/beverages.jpg'),
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
  {
    id: 4,
    name: 'Chinese',
    image: require('app/assets/images/categories/chinese.jpg'),
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
  {
    id: 5,
    name: 'North Indian',
    image: require('app/assets/images/categories/northindian.jpg'),
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
  {
    id: 6,
    name: 'Bakery',
    image: require('app/assets/images/categories/bakery.png'),
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
  {
    id: 7,
    name: 'Italian',
    image: require('app/assets/images/categories/italian.jpg'),
    foodList: [
      {
        id: 1,
        name: 'chilli potato',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 3,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 2,
        name: 'chilli gobhi',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 2,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 3,
        name: 'chilli paneer',
        amount: 120,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 4,
        name: 'veg noodles',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: true,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 5,
        name: 'butter noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 6,
        name: 'paneer noodles',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 7,
        name: 'singapore noodles',
        amount: 90,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 8,
        name: 'veg momos steamed',
        amount: 60,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 9,
        name: 'veg momos fried',
        amount: 70,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 10,
        name: 'paneer momos steamed',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
      {
        id: 11,
        name: 'paneer momos fried',
        amount: 80,
        quantity: 0,
        veg: true,
        ratings: 4,
        popular: false,
        image: require('app/assets/images/categories/chinese.jpg'),
      },
    ],
  },
];
